# Locates the hxcpp haxelib and provides fried_add_hxcpp_executable(), which
# compiles the C++ generated by `haxe ... -cpp <dir> -D no-compilation`
# together with the hxcpp runtime, using CMake instead of hxcpp's own build
# tool (`haxelib run hxcpp Build.xml`).
#
# The runtime/std source lists and compiler defines below were derived by
# inspecting a real `haxelib run hxcpp Build.xml` invocation for hxcpp 4.3.2
# on Linux64. If the hxcpp version changes, re-run a plain
# `haxe -cp src -main Main -cpp <dir>` build once (without -D no-compilation)
# and diff its compiler output against this file.

if(NOT HXCPP_ROOT)
    find_program(HAXELIB_EXECUTABLE haxelib REQUIRED)

    execute_process(
        COMMAND ${HAXELIB_EXECUTABLE} path hxcpp
        OUTPUT_VARIABLE _hxcpp_path_output
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _hxcpp_path_result
    )
    if(NOT _hxcpp_path_result EQUAL 0)
        message(FATAL_ERROR "hxcpp haxelib not found. Run: haxelib install hxcpp")
    endif()

    # `haxelib path hxcpp` prints the include path on the first line and a
    # `-D hxcpp=<version>` compiler flag comment on the second; keep the first.
    string(REPLACE "\n" ";" _hxcpp_path_lines "${_hxcpp_path_output}")
    list(GET _hxcpp_path_lines 0 _hxcpp_root)
    set(HXCPP_ROOT "${_hxcpp_root}" CACHE PATH "Path to the hxcpp haxelib")
endif()

set(HXCPP_INCLUDE_DIR "${HXCPP_ROOT}/include")

# hxcpp's own Build.xml calls this group "runtime": the core GC/object model.
set(_hxcpp_runtime_sources
    src/hx/Object.cpp
    src/Array.cpp
    src/hx/CFFI.cpp
    src/hx/Date.cpp
    src/hx/Anon.cpp
    src/hx/Boot.cpp
    src/hx/Interface.cpp
    src/Enum.cpp
    src/hx/Class.cpp
    src/Dynamic.cpp
    src/hx/gc/GcRegCapture.cpp
    src/Math.cpp
    src/hx/Hash.cpp
    src/hx/Thread.cpp
    src/hx/gc/Immix.cpp
    src/hx/Lib.cpp
    src/hx/StdLibs.cpp
    src/hx/Debug.cpp
    src/hx/gc/GcCommon.cpp
    src/String.cpp
)

# hxcpp's own Build.xml calls this group "hxcpp_std": native sys.* support.
set(_hxcpp_std_sources
    src/hx/libs/std/Random.cpp
    src/hx/libs/std/File.cpp
    src/hx/libs/std/Socket.cpp
    src/hx/libs/std/Process.cpp
    src/hx/libs/std/Sys.cpp
)

# Neither compiles, or works, on a console: neither has subprocesses, the Vita's
# sockets are a Sony API rather than the BSD one hxcpp is written against, and
# libnx's do not open until a socketInitializeDefault() the engine never calls.
set(_hxcpp_std_sources_without_console
    src/hx/libs/std/Socket.cpp
    src/hx/libs/std/Process.cpp
)

# Used instead of the generated __files__.cpp because we don't build with
# HXCPP_DEBUGGER (matches Build.xml's `unless="HXCPP_DEBUGGER"` file entry).
set(_hxcpp_no_files_source src/hx/NoFiles.cpp)

# hxcpp's std sources are written against glibc; cmake/newlib/ fills in what
# newlib either declares without implementing or does not ship at all.
set(_hxcpp_newlib_dir "${CMAKE_CURRENT_LIST_DIR}/newlib")

function(fried_apply_newlib_compat sources)
    set_source_files_properties(${sources} PROPERTIES
        INCLUDE_DIRECTORIES "${_hxcpp_newlib_dir}"
        COMPILE_OPTIONS "-include;${_hxcpp_newlib_dir}/posix_extras.h"
    )
endfunction()

# fried_add_hxcpp_executable(<target> <generated_dir>)
#
# <generated_dir> must be the output of
# `haxe -cp <src> -main <Main> -cpp <generated_dir> -D no-compilation`.
function(fried_add_hxcpp_executable target_name generated_dir)
    if(NOT EXISTS "${generated_dir}/Build.xml")
        message(FATAL_ERROR
            "${generated_dir} does not look like a hxcpp -cpp output "
            "directory (no Build.xml found). Run the matching `haxe` build "
            "first."
        )
    endif()

    # Read HXCPP_API_LEVEL back from the actual Haxe compile that produced
    # generated_dir instead of hardcoding it.
    file(STRINGS "${generated_dir}/Options.txt" _api_level_line REGEX "^hxcpp_api_level=")
    string(REPLACE "hxcpp_api_level=" "" _hxcpp_api_level "${_api_level_line}")

    # CONFIGURE_DEPENDS because the directory is written by the Haxe compiler: a
    # new type there would otherwise fail to link until someone reconfigured by
    # hand, with nothing in the error naming the glob as the reason.
    file(GLOB_RECURSE _generated_sources CONFIGURE_DEPENDS "${generated_dir}/src/*.cpp")
    list(FILTER _generated_sources EXCLUDE REGEX "__lib__\\.cpp$")
    list(FILTER _generated_sources EXCLUDE REGEX "__files__\\.cpp$")

    list(TRANSFORM _hxcpp_runtime_sources PREPEND "${HXCPP_ROOT}/" OUTPUT_VARIABLE _runtime_sources)
    set(_std_source_names ${_hxcpp_std_sources})
    if(VITA OR NINTENDO_SWITCH)
        list(REMOVE_ITEM _std_source_names ${_hxcpp_std_sources_without_console})
    endif()

    list(TRANSFORM _std_source_names PREPEND "${HXCPP_ROOT}/" OUTPUT_VARIABLE _std_sources)
    set(_no_files_source "${HXCPP_ROOT}/${_hxcpp_no_files_source}")

    add_executable(${target_name}
        ${_generated_sources}
        ${_no_files_source}
        ${_runtime_sources}
        ${_std_sources}
    )

    target_include_directories(${target_name} PRIVATE "${generated_dir}/include")
    target_include_directories(${target_name} SYSTEM PRIVATE "${HXCPP_INCLUDE_DIR}")

    target_compile_definitions(${target_name} PRIVATE
        HXCPP_API_LEVEL=${_hxcpp_api_level}
        HXCPP_VISIT_ALLOCS
        HX_SMART_STRINGS
    )

    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        target_compile_definitions(${target_name} PRIVATE HXCPP_M64)
    endif()

    if(VITA OR NINTENDO_SWITCH)
        # hxcpp has no target of its own for either console: HX_LINUX and
        # NEKO_LINUX pick its generic POSIX paths, and neither console loads a
        # shared library.
        target_compile_definitions(${target_name} PRIVATE
            HX_LINUX
            NEKO_LINUX
            HXCPP_NO_DYNAMIC_LOADING
        )
        fried_apply_newlib_compat("${_std_sources}")
        target_sources(${target_name} PRIVATE "${_hxcpp_newlib_dir}/posix_extras.cpp")
    elseif(APPLE)
        target_compile_definitions(${target_name} PRIVATE HX_MACOS)
    elseif(WIN32)
        target_compile_definitions(${target_name} PRIVATE HX_WINDOWS)
    else()
        target_compile_definitions(${target_name} PRIVATE HX_LINUX)
    endif()

    target_compile_options(${target_name} PRIVATE
        -fvisibility=hidden -Wno-overflow
    )

    set_source_files_properties(${_runtime_sources} PROPERTIES
        COMPILE_DEFINITIONS "_CRT_SECURE_NO_DEPRECATE;HX_UNDEFINE_H"
    )

    set_source_files_properties("${generated_dir}/src/__main__.cpp" PROPERTIES
        COMPILE_DEFINITIONS "HX_DECLARE_MAIN"
    )

    if(VITA OR NINTENDO_SWITCH)
        # newlib's struct tm has no tm_gmtoff. __SNC__ is one of the defines
        # Date.cpp keys its mktime() fallback off, and uses for nothing else.
        set_property(SOURCE "${HXCPP_ROOT}/src/hx/Date.cpp"
            APPEND PROPERTY COMPILE_DEFINITIONS __SNC__
        )

        target_link_libraries(${target_name} PRIVATE pthread)
    else()
        find_package(Threads REQUIRED)
        target_link_libraries(${target_name} PRIVATE Threads::Threads)
    endif()

    # Pinned, not the minimum target_compile_features() asks for: hxcpp 4.3.2
    # is written for C++17, and in C++20 cpp::VirtualArray::operator== resolves
    # to itself through the reversed candidate.
    set_target_properties(${target_name} PROPERTIES
        CXX_STANDARD 17
        CXX_STANDARD_REQUIRED ON
    )

    if(NOT VITA)
        set_target_properties(${target_name} PROPERTIES POSITION_INDEPENDENT_CODE ON)
    endif()
endfunction()
